### ISSUE TITLE
Calling get_compass interferes with result of get_orientation

### ISSUE THREAD

**Issue by knolleary** [RPi-Distro/python-sense-hat#46]
Hi,

the following code example calls `get_orientation` and prints the result. It behaves as expected as I move the sense-hat around.

```python
from sense_hat import SenseHat
sense = SenseHat()
while True:
    orientation = sense.get_orientation()
    print orientation
```

Now, if I add a call to `get_compass` in the loop, it causes the values of `orientation['pitch']` and `orientation['roll']` to never change:

```python
from sense_hat import SenseHat
sense = SenseHat()
while True:
    orientation = sense.get_orientation()
    print orientation
    compass = sense.get_compass()
```

When running in an interactive shell, if I return to the original while loop, using the same instance of `sense` - then the values continue to be fixed. I have to create a new `sense` object before they start behaving again.

Is this expected behaviour?

**Comment by bennuttall** [comment]
This is due to the fact the IMU config is set within `get_compass()` and we recommend not setting the IMU config continuously in the loop. As per this note in the [source](https://github.com/RPi-Distro/python-sense-hat/blob/master/sense_hat/sense_hat.py#L642):

> If the consuming code always calls this just before reading the IMU the IMU consistently fails to read. So prevent unnecessary calls to IMU config functions using state variables

Also see the [docs on get_compass](http://pythonhosted.org/sense-hat/api/#get_compass)
